### PR TITLE
Jekyll first pass

### PR DESCRIPTION
**Pull request by nschonni**
Took the existing content and put it into Jekyll templates.

TODO:
- Rules are why behind wiki content and should probably have a separate template file
- Replace head/foot elements with HTML5 natives (HTML5Shiv for fallback)
- Use pygments for rule code highlighting?
- Sync remaining wiki content

---

You can test this out locally by installing Jekyll (`gem install jekyll`) and building the site (`jekyll serve`)

### CODE REVIEW

**Comment by XhmikosR** [comment]
@nschonni: can you push this branch to this repo with or without rebasing?

Also, I wonder do we need the master branch? And that new-ui one what it's for?

**Comment by XhmikosR** [comment]
OK, I see now you have deleted your fork.

Too bad, I could try rebasing it. :/

**Comment by nschonni** [comment]
my fork is actually from when this repo was private (so my fork is hidden), but it probably makes sense to redo it since there have been a bunch of changes since the original PR

**Comment by XhmikosR** [comment]
If you still have it, can you make it public? I will try to rebase it myself.

**Comment by nschonni** [comment]
@XhmikosR it's now public

**Comment by XhmikosR** [comment]
@nschonni: thanks, I rebased it.

A few questions before I push
1. How exactly did you beautify style.css?
2. Do we need those new pages you have added here?

**Comment by XhmikosR** [comment]
Here is what I have so far

https://github.com/CSSLint/csslint.net/compare/jekyll

Needs some more backports, cleanup of those new pages and then is ready to be merged.

**Comment by nschonni** [comment]
@XhmikosR looking at the code it looks OK, but I think there is some cruft I just copied over that you can probably clean up (build.xml). You might want to check to see what parts got easier with Jekyll 3, since this might not have even been Jekyll 2 when I kicked it off.

**Pull request closed without merging**
